### ISSUE TITLE
Flutter 1.22.4版本无法使用该插件

### ISSUE THREAD

**Issue by maomao1020** [simplezhli/flutter_2d_amap#15]
The current Dart SDK version is 2.10.4.                                 
                                                                        
Because aimutou depends on flutter_2d_amap from git which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.

**Comment by simplezhli** [comment]
@maomao1020 可以使用未迁移空安全的历史版本：
```
flutter_2d_amap:
    git:
      ref: '35d7c7'
      url: https://github.com/simplezhli/flutter_2d_amap.git
```
